---
main:
  - name: Blog
    identifier: blog
    weight: 1
    url: "/blog"
    params:
      icon: '<i class="fas fa-fw fa-terminal"></i>'
  - name: Noticias
    identifier: Noticias
    weight: 2
    url: "/news"
    params:
      icon: '<i class="fas fa-fw fa-newspaper"></i>'
  - name: Autores
    identifier: autores
    weight: 3
    url: "/authors"
    params:
      icon: '<i class="fas fa-fw fa-heart"></i>'
  - name: Eventos
    identifier: Eventos
    weight: 100
    url: "/events"
    params:
      icon: '<i class="fas fa-fw fa-bug"></i>'
---

